---
galaxy_info:
  role_name: rhdh_auth
  author: Ansible RHDH Automation Team
  description: Acquire RHDH bearer tokens via browser automation
  company: N/A

  license: MIT

  min_ansible_version: "2.9"

  platforms:
    - name: EL
      versions:
        - 8
        - 9
    - name: Ubuntu
      versions:
        - focal
        - jammy

  galaxy_tags:
    - rhdh
    - backstage
    - authentication
    - rbac
    - keycloak

dependencies: []
